name: CI/CD Workflow

on:
  push:
    branches:
      - auto-ci  # Chạy workflow khi có thay đổi ở nhánh auto-ci
  pull_request:
    branches:
      - auto-ci  # Chạy workflow khi có PR tới nhánh auto-ci

jobs:
   build:
    runs-on: ubuntu-latest

    steps:
      # Check out mã nguồn
      - name: Checkout code
        uses: actions/checkout@v3

        # Tạo file .env cho React và NextJS từ GitHub Secrets
      - name: Create .env file for React and Next.js
        run: |
          # Tạo file .env cho ReactJS
          echo "VITE_API_CRAWLER_URL=${{ secrets.VITE_API_CRAWLER_URL }}" >> .env
          echo "VITE_API_URL=${{ secrets.VITE_API_URL }}" >> .env
          
          # Tạo file .env cho Next.js
          echo "NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }}" >> .env
          echo "NEXT_PUBLIC_FRONT_END_URL=${{ secrets.NEXT_PUBLIC_FRONT_END_URL }}" >> .env
          echo "NODE_ENV=${{ secrets.NODE_ENV }}" >> .env

      # Build và Push image cho Backend (NestJS)
      - name: Build and push NestJS image
        working-directory: ./nestjs-backend   # Đảm bảo vào đúng thư mục dự án backend
        run: |
          docker build -t ${{ secrets.REGISTRY_URL }}/${{ secrets.IMAGE_NAME }}-nestjs-api:${{ github.sha }} .
          docker push ${{ secrets.REGISTRY_URL }}/${{ secrets.IMAGE_NAME }}-nestjs-api:${{ github.sha }}

      # Build và Push image cho Frontend (ReactJS)
      - name: Build and push ReactJS image
        working-directory: ./reactjs-admin   # Đảm bảo vào đúng thư mục dự án ReactJS
        run: |
          docker build --build-arg VITE_API_CRAWLER_URL=${{ secrets.VITE_API_CRAWLER_URL }} \
                       --build-arg VITE_API_URL=${{ secrets.VITE_API_URL }} \
                       -t ${{ secrets.REGISTRY_URL }}/${{ secrets.IMAGE_NAME }}-react-admin:${{ github.sha }} .
          docker push ${{ secrets.REGISTRY_URL }}/${{ secrets.IMAGE_NAME }}-react-admin:${{ github.sha }} .

      # Build và Push image cho Frontend (NextJS)
      - name: Build and push NextJS image
        working-directory: ./nextjs-client   # Đảm bảo vào đúng thư mục dự án NextJS
        run: |
          docker build --build-arg NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }} \
                       --build-arg NEXT_PUBLIC_FRONT_END_URL=${{ secrets.NEXT_PUBLIC_FRONT_END_URL }} \
                       --build-arg NODE_ENV=${{ secrets.NODE_ENV }} \
                       -t ${{ secrets.REGISTRY_URL }}/${{ secrets.IMAGE_NAME }}-next-client:${{ github.sha }} .
          docker push ${{ secrets.REGISTRY_URL }}/${{ secrets.IMAGE_NAME }}-next-client:${{ github.sha }} .